[project]
name = "mcp-azure-devops-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-devops>=7.1.0b4",
    "mcp[cli]>=1.7.1",
    "pytest>=8.3.5",
]
